### ISSUE TITLE
How you make the connection between the Contact.t type and its phone numbers

### ISSUE THREAD

**Issue by krzischp** [dannywillems/ocaml-cordova-plugin-contacts#2]
I downoladed the contact plugin, ocaml-cordova-plugin-contacts and I use it with Ocsigen start. My problem is to know how to access the phone numbers of a Contact.t.
For example, here is my function:

let contact myContact=

            let head = match (Cordova_contacts.Contact.phone_numbers) with

              Some(x::_) -> x
              | _ -> raise (Failure "empty")

            in
         
            Eliom_lib.alert "%s%!" (Cordova_contacts.ContactField.value head) (* to display the phone numbers of the first list object*)
        in
        Cordova_contacts.Contacts.pick_contact contact ;

but the Contact.phone_numbers always seems to be empty. Furthermore I don't understand how you make the connection between the Contact.t type and its phone numbers without any access function to its phone numbers.
Thank you in advance.

**Comment by dannywillems** [comment]
Hi @krzischp. Sorry if I didn't answer to your email. It was on my TODO list.
To be honest, I never tried this plugin, just created the binding. Do you have a complete example?

**Comment by krzischp** [comment]
No problem :)  So the function that works in Javascript is:

(*displays the first phone number of the selected contact in the app Contacts*)
navigator.contacts.pickContact(function(contact){
        (*console.log('The following contact has been selected:' + JSON.stringify(contact));*)
	alert(contact.phoneNumbers[0].value); 
    },function(err){
        console.log('Error: ' + err);
    });

(*and the corresponding function in Ocaml should be something like:*)
let%client _ =
        let contact myContact=
            let head = match Cordova_contacts.Contact.phone_numbers with 
              Some(x::_) -> x
              | _ -> raise (Failure "empty")  (*it's oriented here*)
            in
            Eliom_lib.alert "%s%!" (Cordova_contacts.ContactField.value head)
        in
        Cordova_contacts.Contacts.pick_contact contact ;

Where mycontact is a Contact.t.
I don't understand why there is no function to make the Contact.t match with its own phone numbers.
And when I test it, it's always like if  Cordova_contacts.Contact.phone_numbers is empty, whereas my Contacts are not empty. Thanks in advance.

**Comment by dannywillems** [comment]
@krzischp Sorry for the delay. #3 must fix the issue (it is the case in fact as we saw).
I will update it on opam-repository (in the same time, I will add ocaml-js-stdlib because I saw it wasn't done and you need to install it manually).

I suggest you to do an `opam update` tomorrow or in two days, the time the path is done in opam repository.
If you pin the GitHub repository with `opam pin`, you can do immediately `opam update`.

**Comment by dannywillems** [comment]
@krzischp If you have an error when using `opam udpate`, go to the repository I cloned in `/tmp`, and use `make remove`. When the PR is merged, it's ready.
